name: UI Tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cypress run
        run: npm run e2e
      - run: npm ci
      - name: Jest run
        run: npm run test
